# Generated by Django 4.2.4 on 2023-08-22 05:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('population', models.CharField(max_length=50)),
                ('place_class', models.CharField(max_length=50)),
            ],
        ),
    ]
