name: Django run Test

on:
  pull_request:
    paths:
      - 'django/seoulInfoProject/**'
    branches: [ "main", "develop"]

jobs:
  Django-run-Test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd django/seoulInfoProject && pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd django/seoulInfoProject
        python manage.py test
