name: Django to Dev server

on:
  push:
    paths:
      - 'django/seoulInfoProject/**'
    #   - '!django/seoulInfoProject/static/**'
      - '!**.md'
    branches: [ "develop" ]

jobs:
  django-to-dev-server:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
        

    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_HOST }}
        username: ${{ secrets.DEV_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.PROXY_USER }}
        proxy_key: ${{ secrets.SSH_KEY }}
        proxy_port: 22
        script: |
          source git-clone-force.sh > git-clone-force.log